// 数据来源：清客松 PRD（50 支基本股）。price/change/heat 为演示用模拟值。
export type Stock = {
  code: string
  name: string
  realName: string
  sector: string
  price: number
  change: number
  heat: number
  volatility: string
  risk: string
  intro: string
  profit: string
  valuation: string
  events: string[]
}

export const stocks: Stock[] = [
  {
    code: 'APPL', name: '苹果工坊', realName: 'Apple', sector: '消费科技',
    price: 161.97, change: -1.2, heat: 80, volatility: '中低', risk: '中',
    intro: '全球消费电子与生态服务巨头，靠 iPhone、Mac、iPad、可穿戴设备和服务收入形成闭环。游戏里它是“稳健科技龙头”，涨得不一定最快，但抗打能力强。',
    profit: '苹果的盈利能力来自硬件销量、服务订阅和强生态粘性。iPhone 仍是核心收入来源，但 App Store、iCloud、Apple Music 等服务业务能提供更稳定、更高毛利的收入。',
    valuation: '市场给苹果的估值，一部分来自品牌和生态溢价。它不是纯成长股，估值更看重服务收入能否继续增长，以及硬件创新能否重新打开想象空间。',
    events: ['新品发布', '服务收入增长', '供应链扰动', '关税风险'],
  },
  {
    code: 'MICR', name: '微软魔法塔', realName: 'Microsoft', sector: '软件云服务',
    price: 98.92, change: -0.4, heat: 87, volatility: '中', risk: '中高',
    intro: '企业软件、云计算和 AI Copilot 核心玩家，收入结构更偏企业级订阅和云服务。游戏里适合作为“全能型核心资产”。',
    profit: '微软的盈利能力很强，核心来自企业软件订阅、Azure 云服务、Office、Windows 和 AI Copilot 生态。它的收入结构偏企业客户，稳定性较高。',
    valuation: '市场愿意给微软较高估值，是因为它兼具“稳定现金流”和“AI 增长故事”。如果 Azure 或 AI 商业化低于预期，估值会受到压力。',
    events: ['AI 应用落地', 'Azure 增长', '企业软件需求', '云资本开支'],
  },
  {
    code: 'ALPH', name: '谷歌图书馆', realName: 'Alphabet / Google', sector: '互联网广告',
    price: 114.04, change: -5.4, heat: 64, volatility: '中', risk: '中',
    intro: '搜索广告、YouTube、Android 与 Google Cloud 构成主线，AI 能力强，但广告周期和搜索入口变化会带来波动。',
    profit: '谷歌的盈利能力主要来自搜索广告、YouTube 广告和 Google Cloud。搜索广告现金流强，但 AI 搜索可能改变用户入口。',
    valuation: '谷歌估值的核心矛盾是：它既有强广告现金流，又面临 AI 重塑搜索入口的挑战。市场会在“护城河强”和“入口被冲击”之间反复定价。',
    events: ['搜索广告回暖', 'AI 搜索竞争', '云业务增长', '监管调查'],
  },
  {
    code: 'AMAZ', name: '亚马逊商会', realName: 'Amazon', sector: '电商云计算',
    price: 56.09, change: -5.6, heat: 62, volatility: '中', risk: '中高',
    intro: '电商、AWS 云、广告和物流体系叠加，零售规模大但利润弹性更多来自 AWS 和广告。Amazon 2025 年报提到零售业务接近 6000 亿美元 topline，且 AI 资本开支对自由现金流有影响。(Q4 CDN)',
    profit: '亚马逊表面是电商公司，但利润弹性更多来自 AWS 云、广告和会员生态。零售业务规模大，利润率相对低；云和广告业务更赚钱。',
    valuation: '亚马逊估值取决于市场愿不愿意相信 AWS、广告和 AI 基建投入能继续带来高质量利润。如果资本开支过高，短期估值会承压。',
    events: ['AWS 增长', 'AI 基建投入', '消费疲软', '物流成本变化'],
  },
  {
    code: 'META', name: '元宇宙广场', realName: 'Meta', sector: '互联网广告',
    price: 164.73, change: -6.5, heat: 61, volatility: '中高', risk: '中高',
    intro: '社交流量和广告变现能力极强，AI 推荐和广告系统是增长引擎，但 Reality Labs 和 AI 投入会消耗利润。',
    profit: 'Meta 的盈利能力主要来自 Facebook、Instagram、WhatsApp 等社交产品的广告变现。广告系统和推荐算法越强，利润释放越明显。',
    valuation: 'Meta 的估值一边看广告基本盘，一边看 AI 和元宇宙投入。市场喜欢它的现金流，但会担心 Reality Labs 和 AI 投资过大拖累利润。',
    events: ['广告复苏', 'AI 推荐效率提升', '元宇宙亏损', '隐私监管'],
  },
  {
    code: 'NVID', name: '英伟达能量核心', realName: 'Nvidia', sector: '半导体',
    price: 186.98, change: -1.9, heat: 82, volatility: '极高', risk: '极高',
    intro: 'AI 芯片和数据中心基础设施核心公司，增长强、热度高，是游戏里的“高攻击高波动英雄”。Nvidia 年报将 Data Center、Gaming、Professional Visualization、Automotive 等作为关键市场，并强调 GPU、CPU、CUDA 和网络技术构成统一架构。(证券交易委员会)',
    profit: '英伟达的盈利能力来自 AI GPU、数据中心加速计算、网络设备和 CUDA 生态。AI 算力需求越强，它的收入和利润弹性越大。',
    valuation: '市场给英伟达的估值包含很强的 AI 增长预期。只要 AI 算力需求持续兑现，估值能被利润增长消化；但如果订单放缓或政策限制加剧，股价容易剧烈波动。',
    events: ['AI 算力需求', 'GPU 供给', '出口限制', '估值回调'],
  },
  {
    code: 'TESL', name: '特斯拉电能车厂', realName: 'Tesla', sector: '新能源车',
    price: 150.36, change: 1.4, heat: 75, volatility: '极高', risk: '高',
    intro: '电动车、储能、FSD、机器人和 Robotaxi 叙事叠加，故事性强但受交付、毛利率和竞争影响大。Tesla 披露其业务包括电动车、能源系统、储能以及 AI、机器人和自动化方向。(证券交易委员会)',
    profit: '特斯拉盈利来自电动车销售、储能、软件服务和未来自动驾驶想象。汽车业务受价格战和毛利率影响大。',
    valuation: '特斯拉估值不只看汽车销量，还包含自动驾驶、机器人、Robotaxi 和能源业务的想象空间。估值弹性很大，但也容易因为交付不及预期而回调。',
    events: ['交付量', '降价', 'Robotaxi', '储能增长', '自动驾驶进展'],
  },
  {
    code: 'AMD', name: '红队芯片铺', realName: 'AMD', sector: '半导体',
    price: 191.34, change: -8.0, heat: 85, volatility: '高', risk: '高',
    intro: 'CPU、GPU、数据中心和游戏芯片公司，是 Nvidia 的重要挑战者。游戏里适合做“成长挑战者”，涨跌跟 AI 芯片竞争格局强相关。',
    profit: 'AMD 的盈利能力来自 CPU、GPU、数据中心芯片和游戏主机芯片。它不是 AI 芯片绝对龙头，但在服务器和 AI GPU 上有挑战者机会。',
    valuation: 'AMD 估值通常反映“追赶英伟达”的预期。如果 AI GPU 订单增长，估值容易被抬高；如果竞争差距扩大，估值会被重新压缩。',
    events: ['AI GPU 订单', '服务器 CPU 增长', 'PC 复苏', '竞争失利'],
  },
  {
    code: 'BROA', name: '博通芯片港', realName: 'Broadcom', sector: '半导体',
    price: 146.67, change: 5.8, heat: 74, volatility: '中高', risk: '中高',
    intro: '半导体、网络芯片、定制芯片和基础设施软件结合，现金流能力较强。游戏里是“AI 网络基础设施商”。',
    profit: '博通盈利能力来自网络芯片、定制 ASIC、无线芯片和基础设施软件。它既有芯片业务，也有软件现金流，结构比较均衡。',
    valuation: '博通估值里包含 AI 网络芯片和定制芯片增长预期，同时也包含软件业务的稳定现金流溢价。市场会关注大客户订单是否持续。',
    events: ['定制 AI 芯片订单', 'VMware 整合', '自由现金流', '客户集中'],
  },
  {
    code: 'TSMC', name: '台积电晶圆厂', realName: 'TSMC', sector: '半导体',
    price: 70.57, change: -0.7, heat: 48, volatility: '中', risk: '中高',
    intro: '全球先进晶圆代工核心玩家，为 AI 芯片、手机芯片和高性能计算芯片提供制造能力。游戏里它是“芯片世界的铸造神殿”。',
    profit: '台积电盈利能力来自先进制程晶圆代工。全球 AI 芯片、手机芯片和高性能计算芯片都依赖它的制造能力。',
    valuation: '台积电估值反映它在全球芯片产业链中的核心地位。估值风险主要来自地缘政治、客户资本开支变化和半导体周期波动。',
    events: ['AI 芯片需求', '先进制程', '地缘风险', '客户订单变化'],
  },
  {
    code: 'ASML', name: '光刻机神殿', realName: 'ASML', sector: '半导体设备',
    price: 31.85, change: 2.0, heat: 59, volatility: '中', risk: '中高',
    intro: '高端光刻机关键供应商，是先进制程扩产的核心装备商。游戏里它不是爆发最快，但稀缺性极强。',
    profit: 'ASML 的盈利能力来自高端光刻机，尤其是先进制程所需的 EUV 设备。它的设备稀缺性很强。',
    valuation: 'ASML 估值来自“先进制程不可替代”的稀缺溢价。但如果出口限制、客户扩产放缓或半导体周期下行，估值会受到影响。',
    events: ['EUV 订单', '半导体扩产', '出口限制', '周期下行'],
  },
  {
    code: 'QUAL', name: '高通通信塔', realName: 'Qualcomm', sector: '半导体',
    price: 28.12, change: 4.4, heat: 48, volatility: '中', risk: '中',
    intro: '手机芯片和通信专利授权双主线，同时拓展汽车和 IoT。Qualcomm 2025 10-K 披露主要通过 QCT 半导体和 QTL 授权业务经营。(Q4 CDN)',
    profit: '高通盈利来自手机芯片、通信专利授权、汽车芯片和 IoT。专利授权业务利润率较高，芯片业务受手机周期影响。',
    valuation: '高通估值相对更看重手机换机周期、汽车芯片增长和专利授权稳定性。它不像 AI 芯片股那么热，但也因此估值波动相对可控。',
    events: ['手机换机潮', '车载芯片增长', '授权纠纷', '安卓需求'],
  },
  {
    code: 'INTE', name: '蓝队芯片城', realName: 'Intel', sector: '半导体',
    price: 89.45, change: -3.5, heat: 99, volatility: '高', risk: '中',
    intro: '老牌 CPU 巨头，正在推进数据中心、AI 和 Foundry 转型。游戏里它是“修复型老牌巨人”，机会和风险都来自转型执行。Intel 2025 披露全年收入基本持平，并提到 18A 进入高量产推进。(英特尔)',
    profit: 'Intel 盈利能力来自 PC、服务器 CPU 和制造业务，但近年转型压力较大。它需要证明制程、代工和 AI 产品能重新提升竞争力。',
    valuation: 'Intel 估值更像“老牌巨人修复故事”。市场不会只看现在利润，而会看转型是否成功；如果制程推进顺利，估值可能修复，反之会被继续压低。',
    events: ['Foundry 进展', '数据中心复苏', '制程延期', '重组消息'],
  },
  {
    code: 'ARM', name: '芯片架构学院', realName: 'Arm', sector: '半导体',
    price: 181.33, change: 4.5, heat: 99, volatility: '高', risk: '高',
    intro: '轻资产授权和版税模式，芯片架构广泛用于手机、边缘设备和低功耗计算。Arm 披露其模式包括授权收入和基于芯片出货的版税收入。(证券交易委员会)',
    profit: 'Arm 盈利来自芯片架构授权和版税。它不是直接卖芯片，而是通过授权模式参与手机、AI、汽车和边缘设备增长。',
    valuation: 'Arm 估值通常带有轻资产、高毛利、AI 边缘设备增长的溢价。但如果授权增长低于预期，较高估值会变得敏感。',
    events: ['AI PC', '手机芯片', '边缘 AI', '授权增长'],
  },
  {
    code: 'MIC1', name: '美光记忆矿', realName: 'Micron', sector: '半导体',
    price: 139.17, change: 15.8, heat: 66, volatility: '极高', risk: '中高',
    intro: 'DRAM、NAND 和 HBM 存储厂商，受 AI 服务器和内存价格周期影响很大。Micron 2025 财报材料称收入增长接近 50%，AI 推动存储需求。(Micron Technology)',
    profit: '美光盈利来自 DRAM、NAND 和 HBM 存储。存储价格周期性很强，AI 服务器需求会拉动高端存储。',
    valuation: '美光估值会随着存储周期变化剧烈波动。行业上行时市场愿意提前定价利润改善；周期下行时，即使公司长期重要，估值也会被压制。',
    events: ['HBM 需求', '存储涨价', '库存周期', '价格下跌'],
  },
  {
    code: 'APP1', name: '应材装备铺', realName: 'Applied Materials', sector: '半导体设备',
    price: 153.19, change: -0.1, heat: 57, volatility: '中高', risk: '中',
    intro: '半导体制造设备大厂，覆盖沉积、刻蚀、检测等制造环节。游戏里它是“芯片扩产卖铲人”。',
    profit: '应用材料盈利来自半导体制造设备，是晶圆厂扩产时的重要供应商。它的收入与全球芯片资本开支密切相关。',
    valuation: '估值主要反映半导体扩产周期。如果 AI 带动晶圆厂增加资本开支，估值会受益；如果客户减少设备采购，估值会承压。',
    events: ['晶圆厂扩产', 'AI 资本开支', '半导体周期', '设备订单下滑'],
  },
  {
    code: 'LAMR', name: '泛林刻蚀工坊', realName: 'Lam Research', sector: '半导体设备',
    price: 51.36, change: -2.4, heat: 81, volatility: '中高', risk: '中',
    intro: '以刻蚀和沉积设备见长，先进芯片制造离不开这类设备。Lam 2025 年报强调沉积和刻蚀是半导体制造进步的关键环节。(投资者大厅)',
    profit: 'Lam Research 盈利来自刻蚀、沉积等关键设备，尤其受存储和先进制程投资影响。',
    valuation: '它的估值跟半导体设备周期高度相关。市场会提前交易存储复苏和先进制程扩产，也会提前反映订单下滑风险。',
    events: ['存储扩产', '先进制程', '设备订单', '周期下行'],
  },
  {
    code: 'MARV', name: '美满数据桥', realName: 'Marvell', sector: '半导体',
    price: 18.04, change: 2.1, heat: 74, volatility: '高', risk: '高',
    intro: '数据中心网络、光互连和定制芯片公司，AI 数据中心越大，对高速互连需求越强。Marvell 2025 Q4 称数据中心收入同比增长 78%。(Marvell Technology, Inc.)',
    profit: 'Marvell 盈利来自数据中心网络芯片、光互连、定制芯片和通信芯片。AI 数据中心扩张会提升它的成长想象。',
    valuation: 'Marvell 估值包含较强 AI 数据中心预期。如果定制芯片和高速互连订单放量，估值会提升；如果客户集中或订单延迟，波动会放大。',
    events: ['定制芯片', '光互连', '云厂商订单', '客户集中'],
  },
  {
    code: 'TEXA', name: '德仪模拟电路', realName: 'Texas Instruments', sector: '半导体',
    price: 66.8, change: 0.7, heat: 72, volatility: '中', risk: '中',
    intro: '模拟芯片和嵌入式处理器公司，服务工业、汽车等长期市场。TI 披露其现金流和 300mm 生产优势支撑商业模式。(Texas Instruments)',
    profit: '德州仪器盈利来自模拟芯片和嵌入式处理器，服务工业、汽车和消费电子等场景。业务没有 AI 芯片那么刺激，但现金流相对稳。',
    valuation: '它的估值更偏成熟制造型科技公司。市场看重长期现金流、工业复苏和产能利用率，而不是短期爆发性增长。',
    events: ['工业复苏', '汽车芯片', '库存周期', '制造投资'],
  },
  {
    code: 'ORAC', name: '甲骨文数据库', realName: 'Oracle', sector: '软件云服务',
    price: 43.37, change: 4.5, heat: 68, volatility: '中', risk: '中',
    intro: '老牌数据库和企业软件公司，云业务和数据库迁移是增长主线。游戏里是“老牌数据库法师”。',
    profit: 'Oracle 盈利来自数据库、企业软件和云基础设施。老客户迁移成本高，数据库业务粘性强。',
    valuation: 'Oracle 估值更看重云转型速度和 AI 基建订单。如果云增长能够持续，老牌企业软件也能获得新的估值想象。',
    events: ['云订单', '数据库迁移', 'AI 云合作', '传统业务放缓'],
  },
  {
    code: 'SALE', name: '销售云旅馆', realName: 'Salesforce', sector: '软件云服务',
    price: 161.32, change: 3.2, heat: 71, volatility: '中高', risk: '中高',
    intro: 'CRM 和企业 SaaS 龙头，正在从传统软件升级到 Agentforce AI Agent 平台。',
    profit: 'Salesforce 盈利来自 CRM 订阅、企业客户续费和数据云服务。客户基础大，但增长速度相比早期 SaaS 已经放缓。',
    valuation: '它的估值核心是“传统 SaaS 能否升级成 AI Agent 平台”。如果 Agentforce 被市场认可，估值会修复；如果 AI 反而压缩软件价值，估值会承压。',
    events: ['Agentforce 进展', '大客户合同', 'AI 替代担忧', '增长指引'],
  },
  {
    code: 'ADOB', name: '创意魔法屋', realName: 'Adobe', sector: '软件云服务',
    price: 65.6, change: 0.7, heat: 68, volatility: '中', risk: '中高',
    intro: '创意软件和数字体验平台，订阅模式稳，但生成式 AI 会同时带来机会和竞争。',
    profit: 'Adobe 盈利来自 Creative Cloud、Document Cloud 和数字体验业务。订阅模式稳定，创意软件用户粘性强。',
    valuation: 'Adobe 估值取决于生成式 AI 是增强它的产品，还是削弱它的护城河。市场会同时定价 Firefly 机会和 AI 竞争风险。',
    events: ['Firefly AI', '订阅涨价', '创意行业需求', 'AI 竞争'],
  },
  {
    code: 'SERV', name: '服务流平台', realName: 'ServiceNow', sector: '软件云服务',
    price: 200.43, change: 4.5, heat: 46, volatility: '中高', risk: '高',
    intro: '企业工作流自动化平台，适合做游戏里的“企业流程操作系统”。订阅收入强，但估值敏感。',
    profit: 'ServiceNow 盈利来自企业工作流自动化订阅，客户通常是大型企业，续费和扩展能力较强。',
    valuation: '它的估值里包含企业 AI 工作流平台的预期。只要订阅增长和 AI 落地顺利，估值有支撑；但高预期也意味着容错率较低。',
    events: ['AI 工作流', '企业 IT 支出', '订阅增长', '估值杀跌'],
  },
  {
    code: 'PALA', name: '帕兰提尔情报局', realName: 'Palantir', sector: '数据AI',
    price: 13.11, change: -7.3, heat: 72, volatility: '极高', risk: '极高',
    intro: '政府和商业数据分析平台，AI 平台 AIP 叙事强，增长和市场情绪都很强。',
    profit: 'Palantir 盈利来自政府和企业数据平台，AI 平台 AIP 带来强增长叙事。它的客户项目通常复杂，客单价高。',
    valuation: 'Palantir 估值包含非常强的 AI 平台预期。市场愿意为高增长买单，但如果商业客户增长或利润兑现慢，股价会非常敏感。',
    events: ['国防订单', '商业客户增长', 'AI 热潮', '估值回调'],
  },
  {
    code: 'SNOW', name: '雪花数据仓', realName: 'Snowflake', sector: '数据AI',
    price: 144.34, change: -7.2, heat: 90, volatility: '高', risk: '高',
    intro: '云数据平台，企业 AI 要先有数据治理，所以它适合做“AI 数据底座”。Snowflake 披露 FY2025 Q4 产品收入同比增长 28%，净收入留存率 126%。(Snowflake)',
    profit: 'Snowflake 盈利能力来自云数据平台，企业把数据迁移到云上后，会持续产生存储和计算消费。',
    valuation: 'Snowflake 估值核心是“AI 时代的数据底座”。如果企业 AI 应用增长，它会受益；但消费型收入波动会让估值不稳定。',
    events: ['AI 数据迁移', '云合作', '消费型收入波动', '客户优化开支'],
  },
  {
    code: 'DATA', name: '数据狗哨站', realName: 'Datadog', sector: '数据AI',
    price: 183.77, change: -9.6, heat: 54, volatility: '高', risk: '高',
    intro: '云监控和可观测性平台，云系统越复杂越需要监控。游戏里是“云端警报员”。Datadog 自称为云时代开发者、IT 运维和业务用户构建监控与安全平台。(Datadog)',
    profit: 'Datadog 盈利来自云监控、可观测性和安全产品。云系统越复杂，企业越需要监控工具。',
    valuation: '它的估值取决于企业云支出能否恢复，以及 AI 运维能否打开新增长。如果客户优化云成本，短期估值会受压。',
    events: ['云迁移', 'AI 运维', '企业预算收缩', '软件估值波动'],
  },
  {
    code: 'MONG', name: '芒果数据库', realName: 'MongoDB', sector: '数据AI',
    price: 117.79, change: -3.9, heat: 51, volatility: '高', risk: '高',
    intro: '面向开发者的数据库平台，Atlas 云数据库是核心增长点。MongoDB 披露 FY2025 Atlas 收入增长 24%。(MongoDB, Inc.)',
    profit: 'MongoDB 盈利来自 Atlas 云数据库和企业订阅。它面向开发者生态，成长性来自应用开发和云迁移。',
    valuation: 'MongoDB 估值反映开发者数据库平台的成长预期。市场会关注 Atlas 增长，如果增长放缓，高估值会迅速收缩。',
    events: ['Atlas 增长', '开发者生态', '数据库竞争', '云优化'],
  },
  {
    code: 'SHOP', name: '独立商店联盟', realName: 'Shopify', sector: '电商云计算',
    price: 70.81, change: 12.3, heat: 62, volatility: '高', risk: '高',
    intro: '帮商家建站、收款、物流和运营的电商基础设施平台。Shopify 披露 2025 Q4 收入增长 31%，自由现金流率 19%。(Q4 Capital)',
    profit: 'Shopify 盈利来自商家订阅、支付、物流和电商工具。它服务中小商家，随着商家交易额扩大而增长。',
    valuation: 'Shopify 估值看重独立站生态和支付业务扩张。消费复苏时估值容易提升，但如果商家增长放缓或竞争加剧，估值会被压制。',
    events: ['商家增长', '消费复苏', '支付业务', '竞争加剧'],
  },
  {
    code: 'ATLA', name: '团队协作工坊', realName: 'Atlassian', sector: '软件云服务',
    price: 116.78, change: 8.7, heat: 96, volatility: '中高', risk: '高',
    intro: 'Jira、Confluence 等团队协作工具为主，开发者和企业团队粘性强。Atlassian 2025 年报称多数收入来自 Jira、Confluence 和 Jira Service Management。(Q4 CDN)',
    profit: 'Atlassian 盈利来自 Jira、Confluence 等团队协作软件，客户粘性较强。云迁移是重要增长来源。',
    valuation: '估值取决于云迁移、AI 协作功能和企业软件预算。它不像 AI 平台那么爆发，但稳定订阅能给估值一定支撑。',
    events: ['云迁移', 'AI 协作', '企业 IT 预算', '增长放缓'],
  },
  {
    code: 'GITL', name: '代码仓库酒馆', realName: 'GitLab', sector: '软件云服务',
    price: 173.04, change: 7.5, heat: 43, volatility: '高', risk: '高',
    intro: 'DevSecOps 一体化平台，服务开发、测试、安全和部署流程。GitLab FY2025 披露四季度收入同比增长 29%。(GitLab Investor Relations)',
    profit: 'GitLab 盈利来自 DevSecOps 平台订阅，覆盖代码管理、CI/CD、安全和部署流程。',
    valuation: 'GitLab 估值看重开发者平台能否在 AI 编程时代保持价值。如果企业继续采用一体化 DevOps，估值有支撑；如果竞争加剧，估值会波动。',
    events: ['DevOps 需求', 'AI 编程', '企业客户增长', 'GitHub 竞争'],
  },
  {
    code: 'CROW', name: '云端守卫队', realName: 'CrowdStrike', sector: '网络安全',
    price: 204.31, change: -2.0, heat: 72, volatility: '高', risk: '高',
    intro: '云原生终端安全平台，订阅收入和 ARR 是核心。游戏里适合做“安全攻击事件受益者”。',
    profit: 'CrowdStrike 盈利来自云原生终端安全订阅和平台扩展。客户越依赖云和远程办公，安全需求越强。',
    valuation: '它的估值反映高增长安全平台预期。安全事件会提高市场关注度，但如果出现产品事故或增长放缓，估值会快速承压。',
    events: ['黑客攻击', '企业安全预算', '平台故障', 'ARR 增速'],
  },
  {
    code: 'CLOU', name: '云盾网络城墙', realName: 'Cloudflare', sector: '网络安全',
    price: 37.18, change: 5.4, heat: 42, volatility: '高', risk: '高',
    intro: 'CDN、网络安全、边缘网络和开发者平台结合，覆盖互联网流量入口。Cloudflare 2025 影响报告称其持续提供互联网安全与性能相关服务。(Cloudflare)',
    profit: 'Cloudflare 盈利来自 CDN、边缘网络、安全防护和开发者平台。它靠全球网络基础设施服务大量互联网流量。',
    valuation: 'Cloudflare 估值包含边缘网络、开发者平台和 AI 推理网络想象。它成长空间大，但盈利兑现速度会影响估值稳定性。',
    events: ['DDoS 攻击', '边缘 AI', '流量增长', '估值回调'],
  },
  {
    code: 'ZSCA', name: '零信任护盾', realName: 'Zscaler', sector: '网络安全',
    price: 24.66, change: -2.2, heat: 98, volatility: '高', risk: '高',
    intro: '零信任安全代表公司，云安全和远程办公安全需求是核心驱动。',
    profit: 'Zscaler 盈利来自零信任访问和云安全订阅。企业上云和远程办公越普遍，它的产品需求越强。',
    valuation: 'Zscaler 估值依赖高增长持续性。如果销售执行、客户预算或指引出现问题，市场会迅速下调估值预期。',
    events: ['零信任采购', 'AI 安全', '企业预算', '利润压力'],
  },
  {
    code: 'PALO', name: '帕洛防火墙', realName: 'Palo Alto Networks', sector: '网络安全',
    price: 53.3, change: 3.2, heat: 80, volatility: '中', risk: '中高',
    intro: '综合型网络安全平台，产品线宽，客户基础强。游戏里是“安全行业重装战士”。',
    profit: 'Palo Alto Networks 盈利来自防火墙、云安全、终端安全和安全运营平台。产品线宽，客户基础大。',
    valuation: '它的估值更像成熟安全龙头，市场看重平台化和 AI 安全增长。如果能持续交叉销售，估值更稳；如果行业增长放缓，也会受到拖累。',
    events: ['大型安全事件', '平台化进展', 'AI 安全产品', '并购整合'],
  },
  {
    code: 'OKTA', name: '身份认证门卫', realName: 'Okta', sector: '网络安全',
    price: 19.08, change: -7.0, heat: 57, volatility: '高', risk: '中高',
    intro: '身份认证和访问管理平台，未来还可以扩展到 AI Agent 身份管理。',
    profit: 'Okta 盈利来自身份认证、权限管理和访问安全。未来 AI Agent 变多后，身份和权限管理会更重要。',
    valuation: 'Okta 估值看重身份安全在企业系统中的基础地位。它不是最高热度 AI 股，但如果 AI Agent 权限管理成为新需求，估值会有想象空间。',
    events: ['身份攻击', 'AI Agent 权限', '企业登录安全', '客户流失'],
  },
  {
    code: 'UNIT', name: '游戏引擎工坊', realName: 'Unity', sector: '游戏娱乐',
    price: 187.35, change: 11.2, heat: 46, volatility: '高', risk: '中高',
    intro: '游戏开发引擎和广告变现平台，业务与游戏行业景气度强相关。Unity 2025 Q4 披露 Create Solutions 收入同比增长。(Unity 投资者关系)',
    profit: 'Unity 盈利来自游戏引擎订阅、广告和开发者工具。它依赖游戏行业景气度和开发者生态。',
    valuation: 'Unity 估值带有“游戏开发基础设施”的想象，但市场会担心增长放缓、商业模式调整和开发者信任问题。',
    events: ['游戏行业复苏', '引擎订阅', '广告需求', '开发者流失'],
  },
  {
    code: 'ROBL', name: '方块宇宙乐园', realName: 'Roblox', sector: '游戏娱乐',
    price: 121.01, change: -18.5, heat: 78, volatility: '极高', risk: '高',
    intro: '用户生成内容、虚拟经济和青少年社交游戏平台。游戏里是“高用户活跃、高波动成长股”。',
    profit: 'Roblox 盈利来自虚拟道具、平台分成和用户时长。年轻用户活跃度是它的核心资产。',
    valuation: 'Roblox 估值取决于用户增长、付费率和虚拟经济想象。它有社区平台潜力，但盈利兑现慢会让估值波动较大。',
    events: ['DAU 增长', '爆款游戏', '未成年人监管', '虚拟经济'],
  },
  {
    code: 'NETF', name: '奈飞影像城', realName: 'Netflix', sector: '游戏娱乐',
    price: 70.75, change: 3.4, heat: 83, volatility: '中', risk: '中',
    intro: '全球流媒体平台，订阅模式成熟，广告业务是新增量。',
    profit: 'Netflix 盈利来自流媒体订阅和广告会员。爆款内容、订阅涨价和广告业务会提升利润。',
    valuation: 'Netflix 估值看重全球订阅增长、广告变现和内容成本控制。它不再是早期高速成长股，更像成熟内容平台。',
    events: ['爆款剧集', '广告增长', '订阅涨价', '内容成本'],
  },
  {
    code: 'SPOT', name: '声波音乐馆', realName: 'Spotify', sector: '游戏娱乐',
    price: 179.22, change: -5.0, heat: 78, volatility: '中', risk: '中',
    intro: '音乐、播客和有声内容平台，订阅收入为主，广告业务补充。',
    profit: 'Spotify 盈利来自音乐订阅、广告、播客和音频内容。用户规模大，但版权成本一直影响利润率。',
    valuation: 'Spotify 估值取决于订阅涨价、广告恢复和版权成本控制。如果利润率改善，市场会更愿意给它估值提升。',
    events: ['订阅增长', '价格上调', '版权成本', '广告疲软'],
  },
  {
    code: 'UBER', name: '优步出行车队', realName: 'Uber', sector: '出行平台',
    price: 128.01, change: 1.7, heat: 75, volatility: '中高', risk: '中',
    intro: '出行、外卖和货运平台，网络效应强，受城市出行和消费需求影响。Uber 2025 年报披露 Mobility、Delivery、Freight 三个经营分部。(Q4 CDN)',
    profit: 'Uber 盈利来自出行业务、外卖配送和平台服务费。规模效应增强后，利润率有改善空间。',
    valuation: 'Uber 估值看重平台规模、订单增长和利润率提升。风险在于监管、司机成本和消费周期变化。',
    events: ['出行复苏', '外卖增长', '监管', '司机成本'],
  },
  {
    code: 'AIRB', name: '爱彼迎旅馆村', realName: 'Airbnb', sector: '出行平台',
    price: 121.68, change: 7.3, heat: 53, volatility: '中高', risk: '中',
    intro: '住宿预订和旅行平台，轻资产但强周期，受旅游需求和监管影响。Airbnb 2025 Q4 披露收入同比增长 12%、预订总额同比增长 16%。(Airbnb Newsroom)',
    profit: 'Airbnb 盈利来自住宿预订抽成，轻资产模式带来较好利润弹性。旅游需求强时表现更好。',
    valuation: 'Airbnb 估值取决于旅游需求、房源增长和城市监管。它有平台网络效应，但监管风险会限制估值扩张。',
    events: ['旅游旺季', '跨境旅行', '城市监管', '消费疲软'],
  },
  {
    code: 'ALIB', name: '阿里云商会', realName: 'Alibaba', sector: '中概互联',
    price: 87.48, change: 7.9, heat: 93, volatility: '高', risk: '中',
    intro: '电商和云计算双主线，AI 云是新增长点，但消费和竞争压力明显。',
    profit: '阿里盈利来自电商平台、云计算、国际电商和本地生活。电商仍是基本盘，AI 云是新的增长故事。',
    valuation: '阿里估值反映“电商修复 + AI 云重估”。如果云收入继续加速，估值会改善；如果电商价格战拖累利润，估值会被压制。',
    events: ['电商复苏', 'AI 云增长', '平台监管', '价格战'],
  },
  {
    code: 'TENC', name: '腾讯企鹅王国', realName: 'Tencent', sector: '中概互联',
    price: 20.82, change: -5.8, heat: 81, volatility: '中', risk: '中',
    intro: '社交、游戏、广告、金融科技和云服务综合平台，现金流强。游戏里是“中国科技核心城堡”。',
    profit: '腾讯盈利来自游戏、社交广告、金融科技、视频号和云服务。微信生态强，游戏现金流稳定。',
    valuation: '腾讯估值来自稳定现金流和 AI 提效预期。它不像小公司那么爆发，但社交生态和游戏能力让估值有底盘。',
    events: ['游戏版号', '广告增长', 'AI 内容生产', '监管变化'],
  },
  {
    code: 'BAID', name: '百度搜索塔', realName: 'Baidu', sector: '中概互联',
    price: 138.57, change: -11.5, heat: 95, volatility: '高', risk: '中',
    intro: '搜索广告基本盘承压，但 AI 云、大模型和自动驾驶提供新叙事。',
    profit: '百度盈利来自搜索广告、AI 云和自动驾驶。搜索广告承压时，AI 云和智能驾驶成为市场关注点。',
    valuation: '百度估值像“传统搜索向 AI 转型”的折价修复故事。如果 AI 云和自动驾驶兑现，估值有修复空间；广告继续下滑会压制估值。',
    events: ['AI 云增长', '广告下滑', '自动驾驶进展', '模型发布'],
  },
  {
    code: 'JDCO', name: '京东物流城', realName: 'JD.com', sector: '中概互联',
    price: 219.18, change: 4.1, heat: 65, volatility: '中高', risk: '中',
    intro: '自营零售和供应链物流能力强，利润率较薄但履约能力是优势。JD.com 2025 Q4 称核心 JD Retail 全年收入和经营利润双位数增长。(JD.Com, Inc.)',
    profit: '京东盈利来自自营零售、供应链物流和平台服务。履约能力强，但利润容易受到价格战和新业务投入影响。',
    valuation: '京东估值看重供应链效率和零售利润率。如果价格战缓和，估值会修复；如果补贴和新业务持续烧钱，估值会承压。',
    events: ['消费复苏', '物流效率', '价格战', '新业务投入'],
  },
  {
    code: 'PDDH', name: '拼多多集市', realName: 'PDD Holdings', sector: '中概互联',
    price: 84.89, change: 6.4, heat: 64, volatility: '极高', risk: '中高',
    intro: '拼多多和 Temu 双平台，增长强但竞争、监管和跨境合规风险高。PDD 投资者关系页面将其描述为拥有多项商业业务的跨国商业集团。(PDD Holdings)',
    profit: 'PDD 盈利来自拼多多和 Temu 的电商交易生态。过去增长很强，但近期竞争、监管和供应链投资正在压缩利润。',
    valuation: 'PDD 估值反映高增长和高不确定性并存。市场喜欢它的增长效率，但会担心低价竞争、跨境监管和利润下滑。',
    events: ['Temu 增长', '低价电商', '监管罚款', '供应链投资'],
  },
  {
    code: 'BILI', name: '哔哩像素剧场', realName: 'Bilibili', sector: '中概互联',
    price: 215.28, change: -4.0, heat: 51, volatility: '高', risk: '中高',
    intro: '年轻人社区、直播、会员、广告和游戏业务组合。游戏里适合做“年轻人情绪股”。',
    profit: 'Bilibili 盈利来自增值服务、广告、直播和游戏。年轻人社区粘性强，但商业化和盈利稳定性仍是核心问题。',
    valuation: 'Bilibili 估值更像“社区平台修复故事”。如果广告和游戏表现改善，估值会修复；如果亏损压力持续，估值会受限。',
    events: ['爆款内容', '广告增长', '游戏上线', '亏损压力'],
  },
  {
    code: 'NETE', name: '网易游戏岛', realName: 'NetEase', sector: '中概互联',
    price: 212.92, change: 2.5, heat: 74, volatility: '中', risk: '中',
    intro: '游戏是核心，音乐、教育等业务补充，内容研发能力强。NetEase 2025 Q1 披露游戏及相关增值服务收入同比增长 12.1%。(NetEase, Inc.)',
    profit: '网易盈利主要来自游戏，音乐、教育和创新业务是补充。游戏研发和长线运营能力是它的核心优势。',
    valuation: '网易估值看重游戏产品周期和现金流稳定性。新游戏爆发会提升估值，但如果缺少爆款，估值扩张空间有限。',
    events: ['新游戏上线', '版号', '玩家流水', '内容周期'],
  },
  {
    code: 'LIAU', name: '理想电动车厂', realName: 'Li Auto', sector: '新能源车',
    price: 64.22, change: 3.0, heat: 45, volatility: '极高', risk: '中高',
    intro: '家庭 SUV 和增程/纯电转型主线，产品定位清晰，但竞争和毛利率波动明显。',
    profit: '理想盈利能力取决于车型销量、单车毛利率和家庭用户定位。它比许多新势力更接近规模化，但仍受价格战影响。',
    valuation: '理想估值反映“高端家庭新能源车”定位和智能驾驶想象。如果交付稳定、毛利率维持，估值有支撑；如果新车型失败，估值会波动。',
    events: ['月交付', '新车型', '价格战', '毛利率变化'],
  },
  {
    code: 'NIO', name: '蔚来换电站', realName: 'NIO', sector: '新能源车',
    price: 124.53, change: -11.9, heat: 60, volatility: '极高', risk: '高',
    intro: '高端电动车、换电网络和服务体系是核心差异化，增长弹性大但盈利压力也大。',
    profit: '蔚来盈利能力受到交付规模、换电网络投入和高端品牌成本影响。服务体验强，但固定投入也比较重。',
    valuation: '蔚来估值包含换电网络、高端品牌和智能电动车想象。市场会期待亏损收窄；如果交付和现金流压力加大，估值会快速承压。',
    events: ['换电网络', '交付量', '品牌升级', '亏损收窄'],
  },
]

export const sectors: string[] = ['消费科技', '软件云服务', '互联网广告', '电商云计算', '半导体', '新能源车', '半导体设备', '数据AI', '网络安全', '游戏娱乐', '出行平台', '中概互联']
